-- Highlight groups for the `mono-slate` colorscheme.
--
-- Rule of the theme: shape carries meaning, colour does not.
-- Grey brightness separates code from noise. Only two hues exist, and both
-- come from hrdx: `bad` (red) for errors and escapes, `busy` (amber) for
-- literals and warnings. Do not add a third hue.

local p = require("zenobius-themes.palettes.mono-slate")

local M = {}

---Build the full highlight table.
---@return table<string, vim.api.keyset.highlight>
function M.groups()
  return {
    -- editor chrome
    Normal = { fg = p.fg, bg = p.bg },
    NormalNC = { fg = p.fg_dim, bg = p.bg },
    NormalFloat = { fg = p.fg, bg = p.bg_float },
    FloatBorder = { fg = p.border, bg = p.bg_float },
    FloatTitle = { fg = p.accent, bg = p.bg_float, bold = true },
    FloatFooter = { fg = p.muted, bg = p.bg_float },
    ColorColumn = { bg = p.bg_float },
    Conceal = { fg = p.faint },
    Cursor = { fg = p.bg, bg = p.fg },
    lCursor = { link = "Cursor" },
    CursorIM = { link = "Cursor" },
    CursorColumn = { bg = p.bg_line },
    CursorLine = { bg = p.bg_line },
    CursorLineNr = { fg = p.fg, bold = true },
    LineNr = { fg = p.faint },
    LineNrAbove = { fg = p.faint },
    LineNrBelow = { fg = p.faint },
    SignColumn = { fg = p.muted, bg = p.none },
    FoldColumn = { fg = p.faint, bg = p.none },
    Folded = { fg = p.muted, bg = p.bg_float },
    Directory = { fg = p.accent },
    EndOfBuffer = { fg = p.bg },
    VertSplit = { fg = p.border },
    WinSeparator = { fg = p.border },
    Whitespace = { fg = p.faint },
    NonText = { fg = p.faint },
    SpecialKey = { fg = p.faint },
    MatchParen = { fg = p.busy, bold = true },
    Visual = { bg = p.bg_sel },
    VisualNOS = { bg = p.bg_sel },
    Search = { fg = p.bg, bg = p.accent },
    IncSearch = { fg = p.bg, bg = p.busy },
    CurSearch = { fg = p.bg, bg = p.busy },
    Substitute = { fg = p.bg, bg = p.bad },
    QuickFixLine = { bg = p.bg_sel },
    Title = { fg = p.fg_bright, bold = true },
    Question = { fg = p.accent },
    MoreMsg = { fg = p.good },
    ModeMsg = { fg = p.fg, bold = true },
    MsgArea = { fg = p.fg },
    MsgSeparator = { fg = p.border },
    ErrorMsg = { fg = p.bad, bold = true },
    WarningMsg = { fg = p.busy },
    WinBar = { fg = p.muted, bg = p.bg },
    WinBarNC = { fg = p.faint, bg = p.bg },

    -- status, tabs, menus
    StatusLine = { fg = p.fg, bg = p.bg_bar },
    StatusLineNC = { fg = p.faint, bg = p.bg_deep },
    TabLine = { fg = p.muted, bg = p.bg_deep },
    TabLineFill = { bg = p.bg_deep },
    TabLineSel = { fg = p.fg_bright, bg = p.bg_bar, bold = true },
    Pmenu = { fg = p.fg_dim, bg = p.bg_float },
    PmenuSel = { fg = p.fg_bright, bg = p.bg_sel, bold = true },
    PmenuKind = { fg = p.muted, bg = p.bg_float },
    PmenuKindSel = { fg = p.accent, bg = p.bg_sel },
    PmenuExtra = { fg = p.faint, bg = p.bg_float },
    PmenuExtraSel = { fg = p.muted, bg = p.bg_sel },
    PmenuSbar = { bg = p.bg_float },
    PmenuThumb = { bg = p.border },
    WildMenu = { link = "PmenuSel" },

    -- diff
    DiffAdd = { fg = p.busy, bg = p.bg_float },
    DiffChange = { fg = p.busy_dim, bg = p.bg_float },
    DiffDelete = { fg = p.muted, bg = p.bg_float },
    DiffText = { fg = p.busy, bg = p.bg_sel, bold = true },
    Added = { fg = p.busy },
    Changed = { fg = p.busy_dim },
    Removed = { fg = p.muted },

    -- spelling
    SpellBad = { sp = p.bad, undercurl = true },
    SpellCap = { sp = p.busy, undercurl = true },
    SpellLocal = { sp = p.good, undercurl = true },
    SpellRare = { sp = p.muted, undercurl = true },

    -- legacy syntax
    Comment = { fg = p.comment, italic = true },
    Constant = { fg = p.busy },
    String = { fg = p.good },
    Character = { fg = p.good },
    Number = { fg = p.busy },
    Boolean = { fg = p.busy, bold = true },
    Float = { fg = p.busy },
    Identifier = { fg = p.fg_dim },
    Function = { fg = p.fg_bright },
    Statement = { fg = p.accent, bold = true },
    Conditional = { fg = p.accent, bold = true },
    Repeat = { fg = p.accent, bold = true },
    Label = { fg = p.accent },
    Operator = { fg = p.muted },
    Keyword = { fg = p.accent, bold = true },
    Exception = { fg = p.bad, bold = true },
    PreProc = { fg = p.muted, bold = true },
    Include = { fg = p.muted, bold = true },
    Define = { fg = p.muted, bold = true },
    Macro = { fg = p.muted, bold = true },
    PreCondit = { fg = p.muted, bold = true },
    Type = { fg = p.fg },
    StorageClass = { fg = p.accent },
    Structure = { fg = p.fg },
    Typedef = { fg = p.fg },
    Special = { fg = p.bad },
    SpecialChar = { fg = p.bad },
    Tag = { fg = p.accent },
    Delimiter = { fg = p.muted },
    SpecialComment = { fg = p.muted, italic = true, bold = true },
    Debug = { fg = p.busy },
    Underlined = { underline = true },
    Bold = { bold = true },
    Italic = { italic = true },
    Ignore = { fg = p.faint },
    Error = { fg = p.bad, bold = true },
    Todo = { fg = p.bg, bg = p.busy, bold = true },

    -- treesitter
    ["@variable"] = { fg = p.fg_dim },
    ["@variable.builtin"] = { fg = p.fg_dim, italic = true },
    ["@variable.parameter"] = { fg = p.fg_dim, italic = true },
    ["@variable.member"] = { fg = p.accent },
    ["@constant"] = { fg = p.busy },
    ["@constant.builtin"] = { fg = p.busy, bold = true },
    ["@constant.macro"] = { fg = p.busy },
    ["@module"] = { fg = p.fg },
    ["@label"] = { fg = p.accent },
    ["@string"] = { fg = p.good },
    ["@string.documentation"] = { fg = p.comment, italic = true },
    ["@string.regexp"] = { fg = p.bad },
    ["@string.escape"] = { fg = p.bad, bold = true },
    ["@string.special"] = { fg = p.bad },
    ["@string.special.url"] = { fg = p.good, underline = true },
    ["@character"] = { fg = p.good },
    ["@character.special"] = { fg = p.bad },
    ["@boolean"] = { fg = p.busy, bold = true },
    ["@number"] = { fg = p.busy },
    ["@number.float"] = { fg = p.busy },
    ["@type"] = { fg = p.fg },
    ["@type.builtin"] = { fg = p.fg, italic = true },
    ["@type.definition"] = { fg = p.fg },
    ["@attribute"] = { fg = p.muted },
    ["@property"] = { fg = p.accent },
    ["@function"] = { fg = p.fg_bright },
    ["@function.builtin"] = { fg = p.fg_bright, italic = true },
    ["@function.call"] = { fg = p.fg_bright },
    ["@function.macro"] = { fg = p.fg_bright, bold = true },
    ["@function.method"] = { fg = p.fg_bright },
    ["@function.method.call"] = { fg = p.fg_bright },
    ["@constructor"] = { fg = p.fg },
    ["@operator"] = { fg = p.muted },
    ["@keyword"] = { fg = p.accent, bold = true },
    ["@keyword.function"] = { fg = p.accent, bold = true },
    ["@keyword.operator"] = { fg = p.accent },
    ["@keyword.import"] = { fg = p.muted, bold = true },
    ["@keyword.return"] = { fg = p.accent, bold = true },
    ["@keyword.exception"] = { fg = p.bad, bold = true },
    ["@punctuation.delimiter"] = { fg = p.muted },
    ["@punctuation.bracket"] = { fg = p.muted },
    ["@punctuation.special"] = { fg = p.bad },
    ["@comment"] = { fg = p.comment, italic = true },
    ["@comment.error"] = { fg = p.bg, bg = p.bad, bold = true },
    ["@comment.warning"] = { fg = p.bg, bg = p.busy, bold = true },
    ["@comment.todo"] = { fg = p.bg, bg = p.accent, bold = true },
    ["@comment.note"] = { fg = p.bg, bg = p.good, bold = true },
    ["@markup.strong"] = { fg = p.fg_bright, bold = true },
    ["@markup.italic"] = { italic = true },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.underline"] = { underline = true },
    ["@markup.heading"] = { fg = p.fg_bright, bold = true },
    ["@markup.quote"] = { fg = p.muted, italic = true },
    ["@markup.math"] = { fg = p.busy },
    ["@markup.link"] = { fg = p.accent },
    ["@markup.link.label"] = { fg = p.accent },
    ["@markup.link.url"] = { fg = p.good, underline = true },
    ["@markup.raw"] = { fg = p.good },
    ["@markup.raw.block"] = { fg = p.good },
    ["@markup.list"] = { fg = p.accent },
    ["@markup.list.checked"] = { fg = p.good },
    ["@markup.list.unchecked"] = { fg = p.muted },
    ["@diff.plus"] = { fg = p.good },
    ["@diff.minus"] = { fg = p.bad },
    ["@diff.delta"] = { fg = p.busy },
    ["@tag"] = { fg = p.accent, bold = true },
    ["@tag.builtin"] = { fg = p.accent, bold = true },
    ["@tag.attribute"] = { fg = p.fg_dim, italic = true },
    ["@tag.delimiter"] = { fg = p.muted },

    -- lsp semantic tokens
    ["@lsp.type.class"] = { link = "@type" },
    ["@lsp.type.decorator"] = { link = "@attribute" },
    ["@lsp.type.enum"] = { link = "@type" },
    ["@lsp.type.enumMember"] = { link = "@constant" },
    ["@lsp.type.interface"] = { link = "@type" },
    ["@lsp.type.macro"] = { link = "@function.macro" },
    ["@lsp.type.method"] = { link = "@function.method" },
    ["@lsp.type.namespace"] = { link = "@module" },
    ["@lsp.type.parameter"] = { link = "@variable.parameter" },
    ["@lsp.type.property"] = { link = "@property" },
    ["@lsp.type.struct"] = { link = "@type" },
    ["@lsp.type.type"] = { link = "@type" },
    ["@lsp.type.typeParameter"] = { link = "@type.definition" },
    ["@lsp.type.variable"] = { link = "@variable" },
    ["@lsp.mod.deprecated"] = { strikethrough = true },
    ["@lsp.mod.readonly"] = { link = "@constant" },

    -- diagnostics
    DiagnosticError = { fg = p.bad },
    DiagnosticWarn = { fg = p.busy },
    DiagnosticInfo = { fg = p.good },
    DiagnosticHint = { fg = p.muted },
    DiagnosticOk = { fg = p.good },
    DiagnosticUnderlineError = { sp = p.bad, undercurl = true },
    DiagnosticUnderlineWarn = { sp = p.busy, undercurl = true },
    DiagnosticUnderlineInfo = { sp = p.good, undercurl = true },
    DiagnosticUnderlineHint = { sp = p.muted, undercurl = true },
    DiagnosticUnderlineOk = { sp = p.good, undercurl = true },
    DiagnosticVirtualTextError = { fg = p.bad, bg = p.bg_float },
    DiagnosticVirtualTextWarn = { fg = p.busy, bg = p.bg_float },
    DiagnosticVirtualTextInfo = { fg = p.good, bg = p.bg_float },
    DiagnosticVirtualTextHint = { fg = p.muted, bg = p.bg_float },
    DiagnosticVirtualTextOk = { fg = p.good, bg = p.bg_float },
    DiagnosticDeprecated = { sp = p.faint, strikethrough = true },
    DiagnosticUnnecessary = { fg = p.faint },

    -- lsp core
    LspReferenceText = { bg = p.bg_sel },
    LspReferenceRead = { bg = p.bg_sel },
    LspReferenceWrite = { bg = p.bg_sel, underline = true },
    LspSignatureActiveParameter = { fg = p.busy, bold = true },
    LspCodeLens = { fg = p.faint, italic = true },
    LspInlayHint = { fg = p.faint, bg = p.bg_float, italic = true },
    LspInfoBorder = { link = "FloatBorder" },

    -- gitsigns
    GitSignsAdd = { fg = p.busy },
    GitSignsChange = { fg = p.busy_dim },
    GitSignsDelete = { fg = p.muted },
    GitSignsAddInline = { fg = p.bg, bg = p.busy },
    GitSignsChangeInline = { fg = p.bg, bg = p.busy_dim },
    GitSignsDeleteInline = { fg = p.bg, bg = p.muted },
    GitSignsCurrentLineBlame = { fg = p.faint, italic = true },

    -- neo-tree
    NeoTreeNormal = { fg = p.fg_dim, bg = p.bg_deep },
    NeoTreeNormalNC = { fg = p.muted, bg = p.bg_deep },
    NeoTreeEndOfBuffer = { fg = p.bg_deep, bg = p.bg_deep },
    NeoTreeWinSeparator = { fg = p.border, bg = p.bg_deep },
    NeoTreeRootName = { fg = p.fg_bright, bold = true },
    NeoTreeDirectoryName = { fg = p.accent },
    NeoTreeDirectoryIcon = { fg = p.muted },
    NeoTreeFileName = { fg = p.fg_dim },
    NeoTreeFileIcon = { fg = p.muted },
    NeoTreeIndentMarker = { fg = p.faint },
    NeoTreeExpander = { fg = p.faint },
    NeoTreeDimText = { fg = p.faint },
    NeoTreeGitAdded = { fg = p.busy },
    NeoTreeGitModified = { fg = p.busy_dim },
    NeoTreeGitDeleted = { fg = p.muted },
    NeoTreeGitConflict = { fg = p.bad, bold = true },
    NeoTreeGitUntracked = { fg = p.muted, italic = true },
    NeoTreeGitIgnored = { fg = p.faint },
    NeoTreeTabActive = { fg = p.fg_bright, bg = p.bg_bar, bold = true },
    NeoTreeTabInactive = { fg = p.muted, bg = p.bg_deep },
    NeoTreeTabSeparatorActive = { fg = p.bg_bar, bg = p.bg_bar },
    NeoTreeTabSeparatorInactive = { fg = p.bg_deep, bg = p.bg_deep },

    -- snacks
    SnacksNormal = { link = "NormalFloat" },
    SnacksWinBar = { fg = p.accent, bg = p.bg_float, bold = true },
    SnacksBackdrop = { bg = p.bg_deep },
    SnacksDashboardHeader = { fg = p.accent, bold = true },
    SnacksDashboardFooter = { fg = p.faint, italic = true },
    SnacksDashboardIcon = { fg = p.muted },
    SnacksDashboardDesc = { fg = p.fg_dim },
    SnacksDashboardKey = { fg = p.busy },
    SnacksDashboardTitle = { fg = p.fg_bright, bold = true },
    SnacksIndent = { fg = p.bg_sel },
    SnacksIndentScope = { fg = p.border },
    SnacksNotifierInfo = { fg = p.good, bg = p.bg_float },
    SnacksNotifierWarn = { fg = p.busy, bg = p.bg_float },
    SnacksNotifierError = { fg = p.bad, bg = p.bg_float },
    SnacksNotifierDebug = { fg = p.muted, bg = p.bg_float },
    SnacksNotifierTrace = { fg = p.faint, bg = p.bg_float },
    SnacksPickerMatch = { fg = p.busy, bold = true },
    SnacksPickerDir = { fg = p.faint },
    SnacksPickerFile = { fg = p.fg_dim },
    SnacksPickerPrompt = { fg = p.accent, bold = true },
    SnacksPickerSelected = { fg = p.busy },
    SnacksPickerTitle = { fg = p.bg, bg = p.accent, bold = true },

    -- fzf-lua
    FzfLuaNormal = { link = "NormalFloat" },
    FzfLuaBorder = { link = "FloatBorder" },
    FzfLuaTitle = { fg = p.bg, bg = p.accent, bold = true },
    FzfLuaCursorLine = { bg = p.bg_sel },
    FzfLuaFzfMatch = { fg = p.busy, bold = true },
    FzfLuaFzfPrompt = { fg = p.accent, bold = true },
    FzfLuaFzfPointer = { fg = p.busy },
    FzfLuaHeaderText = { fg = p.muted },
    FzfLuaHeaderBind = { fg = p.busy },
    FzfLuaPathLineNr = { fg = p.faint },
    FzfLuaPathColNr = { fg = p.faint },

    -- telescope, used by some community modules
    TelescopeNormal = { link = "NormalFloat" },
    TelescopeBorder = { link = "FloatBorder" },
    TelescopeTitle = { fg = p.bg, bg = p.accent, bold = true },
    TelescopeSelection = { bg = p.bg_sel, fg = p.fg_bright },
    TelescopeSelectionCaret = { fg = p.busy },
    TelescopeMatching = { fg = p.busy, bold = true },
    TelescopePromptPrefix = { fg = p.accent },

    -- blink.cmp and nvim-cmp
    BlinkCmpMenu = { link = "Pmenu" },
    BlinkCmpMenuBorder = { link = "FloatBorder" },
    BlinkCmpMenuSelection = { link = "PmenuSel" },
    BlinkCmpLabel = { fg = p.fg_dim },
    BlinkCmpLabelMatch = { fg = p.busy, bold = true },
    BlinkCmpLabelDeprecated = { fg = p.faint, strikethrough = true },
    BlinkCmpLabelDetail = { fg = p.faint },
    BlinkCmpKind = { fg = p.muted },
    BlinkCmpSource = { fg = p.faint, italic = true },
    BlinkCmpDoc = { link = "NormalFloat" },
    BlinkCmpDocBorder = { link = "FloatBorder" },
    BlinkCmpSignatureHelp = { link = "NormalFloat" },
    BlinkCmpSignatureHelpActiveParameter = { fg = p.busy, bold = true },
    BlinkCmpGhostText = { fg = p.faint, italic = true },
    CmpItemAbbr = { fg = p.fg_dim },
    CmpItemAbbrMatch = { fg = p.busy, bold = true },
    CmpItemAbbrDeprecated = { fg = p.faint, strikethrough = true },
    CmpItemKind = { fg = p.muted },
    CmpItemMenu = { fg = p.faint, italic = true },
    CmpGhostText = { fg = p.faint, italic = true },

    -- copilot and other virtual suggestions
    CopilotSuggestion = { fg = p.faint, italic = true },
    CopilotAnnotation = { fg = p.faint },

    -- mini and aerial
    MiniClueBorder = { link = "FloatBorder" },
    MiniClueDescGroup = { fg = p.accent, bold = true },
    MiniClueDescSingle = { fg = p.fg_dim },
    MiniClueNextKey = { fg = p.busy, bold = true },
    MiniClueNextKeyWithPostkeys = { fg = p.bad, bold = true },
    MiniClueSeparator = { fg = p.border },
    MiniClueTitle = { fg = p.bg, bg = p.accent, bold = true },
    AerialLine = { bg = p.bg_sel },
    AerialGuide = { fg = p.faint },

    -- dap and dap-ui
    DapBreakpoint = { fg = p.bad },
    DapLogPoint = { fg = p.good },
    DapStopped = { fg = p.busy },
    DapUIVariable = { fg = p.fg_dim },
    DapUIScope = { fg = p.accent, bold = true },
    DapUIType = { fg = p.fg },
    DapUIValue = { fg = p.good },
    DapUIDecoration = { fg = p.border },
    DapUIThread = { fg = p.good },
    DapUIStoppedThread = { fg = p.busy },
    DapUISource = { fg = p.muted },
    DapUILineNumber = { fg = p.faint },
    DapUIFloatBorder = { link = "FloatBorder" },
    DapUIWatchesEmpty = { fg = p.faint },
    DapUIWatchesValue = { fg = p.good },
    DapUIWatchesError = { fg = p.bad },
    DapUIBreakpointsPath = { fg = p.accent },
    DapUIBreakpointsInfo = { fg = p.good },
    DapUIBreakpointsCurrentLine = { fg = p.busy, bold = true },

    -- treesitter context and illuminate
    TreesitterContext = { bg = p.bg_float },
    TreesitterContextLineNumber = { fg = p.faint, bg = p.bg_float },
    TreesitterContextBottom = { sp = p.border, underline = true },
    IlluminatedWordText = { bg = p.bg_sel },
    IlluminatedWordRead = { bg = p.bg_sel },
    IlluminatedWordWrite = { bg = p.bg_sel, underline = true },

    -- markdown render helpers
    RenderMarkdownCode = { bg = p.bg_float },
    RenderMarkdownCodeInline = { fg = p.good, bg = p.bg_float },
    RenderMarkdownBullet = { fg = p.accent },
    RenderMarkdownQuote = { fg = p.muted },
    RenderMarkdownTableHead = { fg = p.accent, bold = true },
    RenderMarkdownTableRow = { fg = p.fg_dim },
    RenderMarkdownH1Bg = { fg = p.bg, bg = p.accent, bold = true },
    RenderMarkdownH2Bg = { fg = p.fg_bright, bg = p.bg_sel, bold = true },
    RenderMarkdownH3Bg = { fg = p.fg, bg = p.bg_float, bold = true },
    RenderMarkdownH4Bg = { fg = p.fg_dim, bg = p.bg_float },
    RenderMarkdownH5Bg = { fg = p.muted, bg = p.bg_float },
    RenderMarkdownH6Bg = { fg = p.faint, bg = p.bg_float },
  }
end

---Terminal colours, in the order Neovim reads `g:terminal_color_0` to `15`.
---Slots 1, 3, 9 and 11 hold the only two hues; every other slot stays grey.
---@return string[]
function M.terminal()
  return {
    p.bg_bar, -- 0 black
    p.bad, -- 1 red
    p.good, -- 2 green
    p.busy, -- 3 yellow
    p.muted, -- 4 blue
    p.accent, -- 5 magenta
    p.fg_dim, -- 6 cyan
    p.fg, -- 7 white
    p.faint, -- 8 bright black
    p.bad, -- 9 bright red
    p.fg_dim, -- 10 bright green
    p.busy, -- 11 bright yellow
    p.comment, -- 12 bright blue
    p.accent, -- 13 bright magenta
    p.fg_bright, -- 14 bright cyan
    p.fg_bright, -- 15 bright white
  }
end

return M
