-- Scheme repositories catalogued by mcchrish/vim-no-color-collections.
-- `:Lazy sync` installs them. Schemes load on demand by colorscheme name.
return {
  {
    "LazyVim/LazyVim",
    opts = { colorscheme = "phoenix" },
  },
  { "andreasvc/vim-256noir", lazy = true },
  { "Alligator/accent.vim", lazy = true },
  { "silentium-theme/silentium.nvim", lazy = true },
  { "plan9-for-vimspace/acme-colors", lazy = true },
  { "huyvohcmc/atlas.vim", lazy = true },
  { "LuRsT/austere.vim", lazy = true },
  { "chriskempson/base16-vim", lazy = true },
  { "t184256/vim-boring", lazy = true },
  { url = "https://git.sr.ht/~romainl/vim-bruin", name = "vim-bruin", lazy = true },
  { "aditya-azad/candle-grey", lazy = true },
  { "ntk148v/komau.vim", lazy = true },
  { "davidosomething/vim-colors-meh", lazy = true },
  { "pbrisbin/vim-colors-off", lazy = true },
  { "andreypopp/vim-colors-plain", lazy = true },
  { "owickstrom/vim-colors-paramount", lazy = true },
  { "reedes/vim-colors-pencil", lazy = true },
  { "Jorengarenar/vim-darkness", lazy = true },
  { "KKPMW/distilled-vim", lazy = true },
  { "jaredgorski/fogbell.vim", lazy = true },
  { "zekzekus/menguless", lazy = true },
  { "jaredgorski/Mies.vim", lazy = true },
  { "fxn/vim-monochrome", lazy = true },
  { "koron/vim-monochromenote", lazy = true },
  { "Lokaltog/vim-monotone", lazy = true },
  { "robertmeta/nofrils", lazy = true },
  { "n1ghtmare/noirblaze-vim", lazy = true },
  { "YorickPeterse/vim-paper", lazy = true },
  { "ajgrf/parchment", lazy = true },
  { "widatama/vim-phoenix", lazy = true },
  { "axvr/photon.vim", lazy = true },
  { "ewilazarus/preto", lazy = true },
  { "stefanvanburen/rams.vim", lazy = true },
  { "kadekillary/skull-vim", lazy = true },
  { "nikolvs/vim-sunbather", lazy = true },
  { "ryanpcmcquen/true-monochrome_vim", lazy = true },
  { "hardselius/warlock", lazy = true },
  { "pgdouyon/vim-yin-yang", lazy = true },
  { "danishprakash/vim-yami", lazy = true },
  { "cideM/yui", lazy = true },
  { "zaki/zazen", lazy = true },
  { "mcchrish/zenbones.nvim", lazy = true },
  { "vim-scripts/zenesque.vim", lazy = true },
  { "A4-Tacks/weak-black-color.vim", lazy = true },
  { "kvrohit/rasmus.nvim", lazy = true },
  -- lush.nvim is a colorscheme framework dependency used by some schemes.
  { "rktjmp/lush.nvim", lazy = true },
}
